title: Ukie
email: gukandrew[ÆT]gmail[∂øt]com
tagline: Andrew Guk - Personal site & blog
description: >-
  Andrew Guk - Personal site & blog
baseurl: ''
url: 'ukie.me'
lang: 'en'
# theme: minima
plugins:
  - jekyll-feed

sass:
  style: compressed

show_excerpts: true
# rss: 'RSS'

github_username: gukandrew
linkedin_username: andrewguk
# twitter_username: jekyllrb
# youtube_username: gukandrew
# facebook_username: gukandrew
# mastodon:
#   - instance: aa.com
#     username: gukandrew
